{% set version = "1.4.1" %}

package:
  name: eofs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/eofs/eofs-{{ version }}.tar.gz
  sha256: 7b5ce336f06d76f79c29e8615fe551de5f1dcc35203dd4745281cc9468e548df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  requires:
    - pytest
    - pycodestyle
  imports:
    - eofs
    - eofs.examples
    - eofs.multivariate
    - eofs.tests
    - eofs.tools
  commands:
    - pytest --pyargs eofs

about:
  home: https://ajdawson.github.com/eofs
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: EOF analysis in Python

extra:
  recipe-maintainers:
    - ajdawson
    - ocefpaf
