{% set version = "2.0.0" %}

package:
  name: eofs
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/eofs/eofs-{{ version }}.tar.gz
  sha256: 4afecba7dd8076399803b71570d96a12dce237615c6317685f83a206fe70ee57

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy

test:
  requires:
    - python {{ python_min }}
    - pytest
  imports:
    - eofs
    - eofs.examples
    - eofs.multivariate
    - eofs.tests
    - eofs.tools
  commands:
    - pytest --pyargs eofs

about:
  home: https://ajdawson.github.com/eofs
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: EOF analysis in Python

extra:
  recipe-maintainers:
    - ajdawson
    - ocefpaf
