{% set version = "1.3.0" %}

package:
    name: eofs
    version: {{ version }}

source:
    fn: v{{ version }}.tar.gz
    url: https://github.com/ajdawson/eofs/archive/v{{ version }}.tar.gz
    md5: 42279c4dd8c384ae4d6a3745787daabb

build:
  noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy

test:
    requires:
        - pytest
        - pycodestyle
    imports:
        - eofs
        - eofs.examples
        - eofs.multivariate
        - eofs.tests
        - eofs.tools
    commands:
        - pytest --pyargs eofs

about:
    home: https://ajdawson.github.com/eofs
    license: GPL-3.0
    summary: EOF analysis in Python

extra:
    recipe-maintainers:
        - ajdawson
        - ocefpaf
