{% set version = "1.4.0" %}

package:
  name: eofs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/eofs/eofs-{{ version }}.tar.gz
  sha256: 5ae9afc159b8cfb2be476d257fc469b2cdd473c76f5411c508010007a5ae6bd2

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy

test:
  requires:
    - pytest
    - pycodestyle
  imports:
    - eofs
    - eofs.examples
    - eofs.multivariate
    - eofs.tests
    - eofs.tools
  commands:
    - pytest --pyargs eofs

about:
  home: https://ajdawson.github.com/eofs
  license: GPL-3.0
  license_file: COPYING
  summary: EOF analysis in Python

extra:
  recipe-maintainers:
    - ajdawson
    - ocefpaf
