travis:
  secure:
    BINSTAR_TOKEN: KSrHmQU1malYd+s93saTsI58Q/wr+T+ndbjITKFkKD2uKfVQq8JrkAaejh54acC+G6FNP1+31i8vWJw3aP/cSmGM3sUrjaUQlyC6BGIeqVB9a0UMRZEMsgdfokDSg7Uxd2yZgSRZ7rHZAkPRoiTGXxjVcGIVzL7oa79T6rZ7d9DDBna5r78hTCJsu1M+3N/lksBcpqiew3NBMQIjTD5AHNXug2ibIcomf4fBu1mA3/xbTdpoMI2tMY3w0Ijkie9R1z8SRSic/pgpfx4TZR1C/zpKIEJpewVN9HfkaB66+5+3ghDm8bDCsQcxa8GnOAMIrDLvHFvp9fOeMwp3GzuoCeYV78YFngtoisa9udGLI/zmf/Lre5QMLWQF4LnhiGEASzD4GUSxDOpwAfJfRTBjlCXcsPjQK3NL0Dz7Zs8pKCt8geCnecXXgUhB+MQROYQrgF+rjaeZxCUE9cw7B+JNXXJK3MtsmqHG/fYlLMhW3LGHUfdsaf9NHZCMLJW+/oXPLPt+s/fhoRGZnazBG/Bm7/zY/5EE/z4RHV5VGFfwIKxAUGutUIW+zWb2MJkY0StLVsNIyZRrZL+hc1SxLGvSPSSwlUmS1eJZvz2D4ZGL0ze0Eo1tns5v9meI0I4VRwZFMxz6q0AgGDBRtqFbV+3FRYnUu6RzoEQ9KaVtWRa9yMA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
