travis:
  secure:
    BINSTAR_TOKEN: ArNiKwI3nBEuWo8u/muNsDIP4K2UqcUqXBPxBDkAJlB+gBEjiZGuuwV6ljXhWPbOJKkKhFhskWsb0z0YXcq4wbm81cq/S4NrYOioAyamkcL0/dLab4XjbExCo+uF5Ftlqd7juk2/DKsesUCIVUSnN6i+KEfLqO5HaajqErnPDfxB0K9oWwh8wHX15XEKJEI0lsgmm5FYf3X/Q2rEVbq7xw223+PCXj2ucYLcKnmVuv0C0Nzd/PDCM67fliDwuF0+jOy+OspmjeicAcI8rg16QC7go2KNyg1wAJYyQqIkCwF69R56CGEVwlU0XkdgnOJihzYITRt6U/Y3ovWxPfoOMXybvOPXW4PdFzj3HKtzYY/zGtTa3jiccVn4TV7HRbSbpbD4TJnLvURftID/d+ZQ65hthfFMa2yP7HNJy5Mh1bYJQYArVjl2DzYC8iMyi8hEGL+NWGu+YCAckw94zHKWeROmoi6AnUyG/sPPWbfnjOsASxbACBYq1eTRASwquuJQsXLm+L9bN7QOBNgxQgfCkkM5LZn9i55CCGzbjGFpk1MA5YfRF5a1KEb1UEWTWzSXpC6TlJiuBiuy8GldHN/vZbYuRl5u1NLk4AnUL0VybbfaW+RdiarK6DqLM1SVG2BG5Iq/ae7z1zKcIbBMMRymJ7AJPpRjb2Cn9nHbkfNZ8Cs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
